---
- name: Backup MongoDB Databases
  hosts: serverspace_host
  become: yes  # Запуск от имени суперпользователя
  vars:
    backup_dir: "/backups"
    mongo_db_name: "test_db"
  
  tasks:
    - name: Create backup directory if not exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0777'

    # Cold backup MongoDB
    - name: Stop MongoDB service
      service:
        name: mongod
        state: stopped

    - name: Perform cold backup of MongoDB
      command: cp -r /var/lib/mongodb {{ backup_dir }}/mongodb_cold_backup_{{ ansible_date_time.iso8601 }} 

    - name: Start MongoDB service
      service:
        name: mongod
        state: started
  
    # Backup MongoDB - binary format
    - name: Backup MongoDB
      command: mongodump --db {{ mongo_db_name }} --out {{ backup_dir }}/mongodb_backup_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}
      
    # Backup MongoDB - export to JSON format
    - name: Export MongoDB to JSON
      command: mongoexport --db {{ mongo_db_name }} --collection имя_коллекции --out {{ backup_dir }}/mongo_export_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.json
