---
- name: Cold backup PostgreSQL Databases
  hosts: serverspace_host_postgres
  become: yes  # Запуск от имени суперпользователя
  vars:
    postgres_db_name: "mydatabase"
    backup_dir: "/backups"  
  tasks:
    - name: Create backup directory if not exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0777'

    # Cold backup PostgreSQL
    - name: Stop PostgreSQL service
      service:
        name: postgresql
        state: stopped
    
    - name: Wait for PostgreSQL to fully stop
      wait_for:
        timeout: 10  # Ожидание 10 секунд

    - name: Perform cold backup of PostgreSQL
      command: cp -r /var/lib/postgresql/14/main {{ backup_dir }}/postgresql_cold_backup_{{ ansible_date_time.iso8601 }} 

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started

    - name: Wait for PostgreSQL to start
      wait_for:
        port: 5432
        delay: 5  # Задержка перед началом проверки порта
        timeout: 10  # Максимальное время ожидания в секундах
